---

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "php7-tutorial.com"
    root: "/var/www/php7-tutorial.com/public"
    index: "index.php index.html"
    access_log: "/var/log/nginx/php7-tutorial.com.access.log"
    extra_parameters: |
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }