---

- name: Create EC2 instances
  ec2:
    key_name: "{{ app.key_name }}"
    assign_public_ip: "{{ app.public_ip }}"
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    wait: yes
    group: "{{ app.group }}"
    region: "{{ app.region }}"
    instance_type: t2.micro
    image: "{{ image_id }}"
    instance_tags:
      env: "{{ app.env }}"
      name: "{{ app.name }}"
      tag: "{{ source_tag.after }}"
    count_tag:
      env: "{{ app.env }}"
      name: "{{ app.name }}"
      tag: "{{ source_tag.after }}"
    exact_count: "{{ app.instances }}"
  register: ec2
- name: Add all instance public IPs to host group
  add_host: hostname="{{ item.public_ip }}" groups=ec2hosts
  with_items: ec2.tagged_instances
  when: ec2.tagged_instances is defined
- local_action: wait_for port=22 host="{{ item.public_ip }}" delay=5
  with_items: ec2.tagged_instances
  when: app.public_ip == "yes" and ec2.tagged_instances is defined