---

- local_action: wait_for delay=10
- name: Instance Register
  ec2_elb:
    instance_id: "{{ item.id }}"
    ec2_elbs: "elb-{{ app.name | regex_replace('[^a-z0-9]', '-') }}"
    state: "{{ status }}"
    region: "{{ app.region }}"
  with_items: ec2.tagged_instances
