---

nginx_vhosts:
  - listen: "80 default_server"
    server_name: "blog.dev-art.fr"
    root: "/var/www/blog.dev-art.fr"
    index: "index.php index.html index.htm"
    access_log: "/var/log/nginx/blog.dev-art.fr.access.log"
    extra_parameters: |
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }